### ISSUE TITLE
How is this different (needed) when able to do bluebird.promisifyAll? 

### ISSUE THREAD

**Issue by geertbrit** [balassy/couchbase-promise#13]
Not wanting to sound snarky, but how is this useful when you could (probably) just wrap all couchbase node methods with a single `promisifyAll`?

**Comment by balassy** [comment]
Hello @gebrits,

PromisifyAll creates a promisified version for all the methods, even if you use only a few of them, which may have unnecessary memory and performance overhead. The bigger problem is, that the original library may already have Async methods, which makes Bluebird.promisifyAll fail. 

So the original idea was to create a wrapper only for those methods, that are often used, and maybe even make a friendlier interface than what the underlying Couchbase library provides.

Thanks,
Gyuri

**Comment by goatandsheep** [comment]
I think this issue can safely be closed ✅
